### ISSUE TITLE
Initialize views belonging to each activity

### ISSUE THREAD

**Issue by ClaudeHangui** [ddekanski/BottomNavigationViewBetweenActivities#1]
Hello,
I wast just trying your solution to handle BottomNavigationview with activities instead of fragments and it works great....However how would you handle the situation where each of the activities (Home, Dashboard...etc) had separate widgets i.e Buttons, EditText, TextView etc...how/where would we have to initialize those views ?? Is it in the BaseActivity or in the Activity which has those views ??...
If it is the latter in which (callback) method will we initialize them?? Because in each of those activities you return the Id of the view associated to each activity....Assuming each of those activities now have different widgets inside of them how should we handle/initialize them and where should we handle events associated to each widget?

**Comment by ddekanski** [comment]
Everything that belongs to each individual activity should be initialized/handled in that activity. The base activity should only cope with the common elements: the bottom navigation in this case. Notice that onCreate() and other activity lifecycle methods are called within the resulting activities, the only requirement here is to properly call the corresponding base activity methods from them.

**Comment by ClaudeHangui** [comment]
I hear you...so let me try to get this straight: you're saying that I can call again OnCreate method in the corresponding activities ?? If so will I have again to call setContentView method (in the corresponding activities) ?

**Comment by ddekanski** [comment]
You never call the onCreate method (or any of other lifecycle callbacks for that matter), it's called by Android to notify your activities of changes. 

But I think now I'm getting what you're aiming at. First, as you can see in e.g. DashboardActivity, each of activities inheriting from BaseActivity needs to have the getContentViewId() method, where  you pass the content view id of the activity. Second, in order to respond to lifecycle events, you can implement any lifecycle callbacks, just remember to call the BaseActivity's callback methods from them. For instance, if you implement onCreate in your activities, its first command should be super.onCreate().

I recommend getting familiar with the lifecycle callbacks mechanism in Android, it's a fundamental thing for any Android app: https://developer.android.com/guide/components/activities/activity-lifecycle.html.

**Comment by eimanebreja** [comment]
I found this error Attempt to invoke virtual method 'void android.widget.ImageView.setOnClickListener(android.view.View$OnClickListener)' on a null object reference. What should I do?
